### ISSUE TITLE
refreshing simple-tree-table

### ISSUE THREAD

**Issue by MantautasG** [kanety/jquery-simple-tree-table#6]
Hello,

I'd like to ask if there is any possibility to reload or refresh tree-table in case of data update. What i do is that i update certain value of tree-table and try to load the tree again.  Like this : 
![image](https://user-images.githubusercontent.com/28557416/54242439-44b3f500-452d-11e9-9001-7b004408230f.png) i fill my template and try to load tree-table again. After the load i get broken tree structure. Any ideas on how to reload tree data?

**Comment by kanety** [comment]
Could you try calling `.init()` instead of `.simpleTreeTable()` after updating the table?
For example:

```js
// comment out
// $('#competence-table').simpleTeeTable();

$('#competence-table').data('simple-tree-table').init();
```

**Comment by woroagung** [comment]
> Could you try calling `.init()` instead of `.simpleTreeTable()` after updating the table? For example:
> 
> ```js
> // comment out
> // $('#competence-table').simpleTeeTable();
> 
> $('#competence-table').data('simple-tree-table').init();
> ```

i have same issue, and $('#competence-table').data('simple-tree-table').init() is not working, reloading data using ajax, and got broken strucutre, the + and - icon still at the same place, i guess the table is not reloaded, any other information?

**Comment by woroagung** [comment]
well just found solution that i just need to change the data state to empty array before doing requests

```
data = []
... your code to refresh
```
