### ISSUE TITLE
icon position

### ISSUE THREAD

**Issue by ince500** [kanety/jquery-simple-tree-table#7]
Kaneta-san konichiwa!
How can i change icon position to second <td> ?
![icon](https://user-images.githubusercontent.com/32541546/55061660-7c2eaf80-509e-11e9-99a5-56712c8e1966.jpg)

**Comment by kanety** [comment]
Could you try setting `iconPosition`?
For example:

```js
$('...').simpleTreeTable({
  iconPosition: 'td.SECOND_POSITION_CLASS'
});
```
